import pandas as pd

# Function for loading data from originations datasets
def load_origination_data(filepath):
    df = pd.read_csv(filepath, sep='|', header=None,
                     names=['CREDIT_SCORE', 'FIRST_PAYMENT_DATE', 'FIRST_TIME_HOMEBUYER_FLAG', 'MATURITY_DATE', 'MSA_OR_MET_DIV',
           'MI_PERCENT', 'NUMBER_OF_UNITS', 'OCCUPANCY_STATUS', 'ORIGINAL_CLTV', 'ORIGINAL_DTI_RATIO', 
           'ORIGINAL_UPB', 'ORIGINAL_LTV', 'ORIGINAL_INTEREST_RATE', 'CHANNEL', 'PPM_FLAG', 
           'AMORTIZATION_TYPE', 'PROPERTY_STATE', 'PROPERTY_TYPE', 'POSTAL_CODE', 'LOAN_SEQUENCE_NUMBER',
           'LOAN_PURPOSE', 'ORIGINAL_LOAN_TERM', 'NUMBER_OF_BORROWERS', 'SELLER_NAME', 'SERVICER_NAME',
           'SUPER_CONFORMING_FLAG', 'PRE_RELIEF_LOAN_NUMBER', 'PROGRAM_INDICATOR', 'RELIEF_REFI_INDICATOR', 'PROP_VALUATION_METHOD',
           'IO_INDICATOR', 'MI_CANCEL_INDICATOR'])

    return df

# Function for loading data from performance datasets
def load_performance_data(filepath):
    df = pd.read_csv(filepath, sep='|', header=None,
                     names=['LOAN_SEQUENCE_NUMBER', 'MONTHLY_REPORTING_PERIOD', 'CURRENT_ACTUAL_UPB', 'CURRENT_DELINQUENCY_STATUS', 'LOAN_AGE',
            'MONTHS_REMAINING', 'DEFECT_SETTLEMENT_DATE', 'MODIFICATION_FLAG', 'ZERO_BALANCE_CODE', 'ZERO_BALANCE_EFFECT_DATE',
            'CURRENT_INTEREST_RATE', 'CURRENT_NON_INTEREST_UPB', 'DDLPI', 'MI_RECOVERIES', 'NET_SALE_PROCEEDS', 
            'NON_MI_RECOVERIES', 'TOTAL_EXPENSES', 'LEGAL_COSTS', 'MAINTENANCE_PRESERVE_COSTS', 'TAXES_AND_INSURANCE',
            'MISC_EXPENSES', 'ACTUAL_LOSS_CALC', 'CUMULATIVE_MOD_COST', 'STEP_MOD_FLAG', 'PAYMENT_DEFERRAL',
            'ELTV', 'ZERO_BALANCE_REMOVAL_UPB', 'DELINQUENT_ACCRUED_INTEREST', 'DELINQUENCY_DUE_TO_DISASTER', 'BORR_ASSIST_STATUS_CODE',
            'CURRENT_MONTH_MOD_COST', 'INTEREST_BEARING_UPB'])

    return df
